logo_url:
  default: ""
  type: string
  description: "The default logo"
mobile_logo_url:
  default: ""
  type: upload
  description: "Defaults to logo_url if not set"
logo_url_dark:
  default: ""
  type: upload
  description: "Defaults to logo_url if not set"
mobile_logo_url_dark:
  default: ""
  type: upload
  description: "Defaults to logo_url_dark if not set, then falls back to mobile_logo_url"
logo_alt:
  default: "Site Name"
  type: string
  description: "The alt text to display for the large logo image"
logo_height:
  default: 120
  type: integer
  description: "Set the height of the large logo"
  min: 0